<!doctype html>
<html lang="en" data-critters-container>
<head>
  <meta charset="utf-8">
  <title>Angular16</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.ef46db3751d8e999.css"></head>
<body>
	<h1>FTL-Angular</h1>
  <app-root></app-root>
<script src="runtime.aa55a760117fc18c.js" type="module"></script><script src="polyfills.62778664f284c5af.js" type="module"></script><script src="main.afd353a18cac06f5.js" type="module"></script></body>