<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Angular16</title>
<base href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="favicon.ico">

	<link rel="stylesheet" href="../angular-16/styles.ef46db3751d8e999.css">

</head>
<body>
	<h1>FTL-Angular-1</h1>
	<app-root></app-root>
	
		
			<script src="../angular-16/runtime.aa55a760117fc18c.js" type="text/javascript"></script>
		
	
		
			<script src="../angular-16/polyfills.62778664f284c5af.js" type="text/javascript"></script>
		
	
		
			<script src="../angular-16/main.afd353a18cac06f5.js" type="text/javascript"></script>
		
	
</body>
</html>


